version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: sva-nginx
    working_dir: /application
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../:/application
    ports:
      - '80:80'
    depends_on:
      - php-fpm
    networks:
        - servers-network

  php-fpm:
    build: php
    container_name: sva-php-fpm
    working_dir: /application
    volumes:
      - ../:/application
      - ./php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    ports:
      - '9000'
    links:
      - postgres
    networks:
        - servers-network

  db:
    container_name: mysql8_test
    image: mysql:8.2
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: servers
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - './db/data:/var/lib/mysql'
      - './db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './db/sql:/docker-entrypoint-initdb.d'
    networks:
      - servers-network

networks:
    servers-network:
        driver: bridge
